FROM rust:1.67 as builder
WORKDIR /app
COPY ./src ./src
COPY ./Cargo.toml .
COPY ./Cargo.lock .
COPY ./.env.prod ./.env
RUN export $(cat .env | xargs) && cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/bot /usr/local/bin/bot
CMD ["bot"]
