version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
      - ./Cargo.toml:/app/Cargo.toml:rw
      - ./Cargo.lock:/app/Cargo.lock:rw
      - ./.env.dev:/app/.env:rw
    entrypoint: cargo run --bin bot
    restart: always
    tty: true
    env_file:
      - .env.dev
