[config]
skip_core_tasks = true

[env.ENV]
source = "${CARGO_MAKE_PROFILE}"
default_value = "dev"
mapping = { prod = "prod", production = "prod", stage = "stage" }

[env]
DOCKER_ARGUMENTS = "-f docker-compose.${ENV}.yaml"

[tasks.help]
description = "Show help"
command = "cargo"
args = ["make", "--list-all-steps"]

[tasks.build]
category = "Docker"
description = "Build docker images"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "build", "${@}"]

[tasks.up]
category = "Docker"
description = "Create and Start docker containers"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "up", "-d", "${@}"]

[tasks.ps]
category = "Docker"
description = "List running docker containers"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "ps", "${@}"]

[tasks.restart]
category = "Docker"
description = "Restart docker containers"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "restart", "${@}"]

[tasks.logs]
category = "Docker"
description = "Show docker logs"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "logs", "--tail", "100", "-f", "${@}"]

[tasks.exec]
category = "Docker"
description = "Execute command in docker container"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "exec", "${@}"]

[tasks.rm]
category = "Docker"
description = "Remove docker containers"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "rm", "${@}"]

[tasks.stop]
category = "Docker"
description = "Stop docker containers"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "stop", "${@}"]

[tasks.down]
category = "Docker"
description = "Stop and remove docker containers"
command = "docker-compose"
args = ["@@split(DOCKER_ARGUMENTS, )", "down"]
